Week 1 Master Assignment 
Python Fundamentals + NumPy Foundations 
Name: Vinod Kumar Vemagal Raviprasad
Learner ID: 18072
Course: Data Science
Date: 21/07/2026

Section A

1.What is the difference between the is operator and the == operator? Give one example where two variables return True for == but False for is?

The is operator used to check identity of two variables pointing for same object in memory
The == operator is used for checking equality of two objects for example to check whether both objects have same values 
Example: 
a = [1, 2, 3]
b = [1, 2, 3]
print(a==b) is true because values are equal & print(a is b)  is false because a and b have different memory locations

In [1]:
a = [1, 2, 3]
b = [1, 2, 3]
print(a==b)

True


In [2]:
a = [1, 2, 3]
b = [1, 2, 3]
print(a is b)

False


2.	Classify the following as Mutable or Immutable: list, tuple, set, dictionary, str, int, float, bool, frozen set. Explain in one line WHY immutability matters in real code?

Mutable are list, set and dictionary
Immutable are tuple, string, integer, float, Boolean, frozen set
Immutability matters in real code because immutable objects are safe to use as dictionary keys. Since, their value cannot change after creation.

3.	Predict the output of print(0.1 + 0.2 == 0.3). Then explain WHY this happens.
    
This happens because floating point numbers are stored in binary. For example the sum 0.1 + 0.2 might be stored as 0.30000004, 
which is not exactly equal to 0.3. Because It’s a limitation of computer representation

In [3]:
print(0.1+0.2==0.3)

False


4.	Both list and tuple can store ordered collections. Give 3 concrete situations where you would CHOOSE a tuple over a list, and explain the reasoning behind each.

Three situations where a tuple is better than a list:
Fixed data that should not change for example storing GPS coordinates (12.97, 77.59). Because tuples are immutable So, they cannot be modified.
Performance and efficiency for example, storing configuration constants like True, False, None. Because tuples are lighter and faster to access compared to lists.

5.	Why is dictionary lookup O(1) on average while searching for a value in a list using `in` is O(n)? Explain in plain English without using the word "hash" - 
then explain it again WITH the word "hash".
    
A list searches elements one by one until it finds the required value, so the search time increases with the size of the list, making it O(n). A dictionary 
organizes data so Python can directly locate a key without checking every item, making lookup O(1) on average. 
    
A dictionary uses a hash function to convert a key into a memory location, allowing Python to access the value directly instead of searching through all 
items. Because of this hash-based lookup, dictionary access is O(1) on average, whereas searching a list requires checking elements one by one, resulting in O(n) time.


6.	What is the difference between `range()` and `numpy.arange()`? Mention at least 3 differences, one of them should involve floats.
    
range() supports only integers, where as numpy.arange() supports float also. 
range() produces a simple range object, But, numpy.arange() produces a NumPy array. 
range() is suitable for basic iteration in loops and numpy.arange() is optimized for numerical work


7.	What is the difference between `list.append(x)`, `list.extend(x)`, and `list.insert(i, x)`? For each, show what happens when `x = [4, 5]` is 
added to `a = [1, 2, 3]`.
    
list.append(x) adds the object x as a single element at the end

list.extend(x) adds each element individually to the list.

list.insert(i, x) inserts x at a specific position i.

In [5]:
a = [1, 2, 3]
a.append([4, 5])
print(a)

b = [1, 2, 3]
b.extend([4, 5])
print(b)

c = [1, 2, 3]
c.insert(1, [4, 5])
print(c)

[1, 2, 3, [4, 5]]
[1, 2, 3, 4, 5]
[1, [4, 5], 2, 3]


8.	What does this line do, and what are the values of a, b, c after execution? a, *b, c = [10, 20, 30, 40, 50] 
Now, what happens if you write: `a, *b, c = [10, 20]`? And `a, *b, c = [10]?

a, *b, c = [10, 20, 30, 40, 50] In this first value is assigned to a, the last value is assigned to c, and all the remaining middle values are 
collected into the list b. So, after execution, a = 10, b = [20, 30, 40], and c = 50.
    
If we write a, *b, c = [10, 20], Python assigns the first value to a and the last value to c. Since there are no values left in between, 
b becomes an empty list. The values are a = 10, b = [], and c = 20.
    
If we write a, *b, c = [10], Python raises a Value error, because there are not enough values to assign both a and c. At least two elements are 
required, so the assignment fails.

9. Explain the difference between `/`, `//`, `%`, and `**` operators in Python. For each, give the output of the operation when applied to (-7, 2).

Division / : Performs true division, returns a float.
Floor Division // : Performs division but rounds down to the nearest integer.
Modulus % : Returns the remainder after division, with the sign following the divisor.
Exponentiation ** : Raises the first number to the power of the second.

In [8]:
print(-7/2)
print(-7//2)
print(-7%2)
print(-7**2)

-3.5
-4
1
-49


10. Why is NumPy significantly faster than Python lists for numerical operations? Give 3 reasons, at 
least one should mention memory layout.

NumPy is faster than Python lists because:
Memory layout: NumPy stores data in continuous memory blocks with fixed types, while lists store scattered references.
Vectorization: NumPy applies operations to whole arrays at once, lists need slow loops.
C backend: NumPy uses optimized C/Fortran code, lists run in Python only.

Section B - Output Prediction

Q11. Predict the output. Why does the second line behave differently from the first? 

Expected Output: 
print(matrix1)   #[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
print(matrix2)   #[[99, 0, 0], [99, 0, 0], [99, 0, 0]]

In [10]:
matrix1 = [[0] * 3 for _ in range(3)] 
matrix2 = [[0] * 3] * 3 
matrix1[0][0] = 99 
matrix2[0][0] = 99 
print(matrix1) 
print(matrix2) 

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


matrix1 creates separate inner lists and only the first row changes.
matrix2 reuses the same inner list three times and updating one row updates all.

Q12. Predict the output: 
x = [1, 2, 3]
y = x
x = x + [4]
print("x =", x)   Expected output: [1, 2, 3, 4]
print("y =", y)   [1, 2, 3]

a = [1, 2, 3]
b = a
a += [4]
print("a =", a)    [1, 2, 3, 4]
print("b =", b)    [1, 2, 3, 4]

Now answer: Why do `x = x + [4]` and `a += [4]` behave differently?

In [11]:
x = [1, 2, 3] 
y = x 
x = x + [4] 
print("x =", x) 
print("y =", y) 
  
a = [1, 2, 3] 
b = a 
a += [4] 
print("a =", a) 
print("b =", b) 

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


x = x + [4] creates a new list object and rebinds x and leaves y pointing to the old list.
a += [4] modifies the same list, so both a and b shows  the same change.

13. Predict the output. What is the value of `i` after the loop ends, and why? 
for i in range(5): 
    pass 
print(i) - expected output is 4
  
for j in range(0): 
    pass 
print(j)  - Expected output might show error

In [12]:
for i in range(5):
    pass
print(i)   

for j in range(0):
    pass
print(j)   

4


NameError: name 'j' is not defined

In the first loop, i takes values 0,1,2,3,4 so after the loop ends it remains 4.
In the second loop, range(0) has no iteration, So it shows a error.

Q14. Predict the output of each print statement. Then state which lines will raise an error (if any). 
print("10" + "20")          expected output: "1020"
print(10 + 20)                                30
print("10" * 3)                              "101010"
print(10 * "3")                              "3333333333"
print("10" + 20)                             string and int cannot be added
print(int("10") + 20)                        string is converted into int and added with 20, so it shows 30

In [13]:
print("10" + "20") 
print(10 + 20) 
print("10" * 3) 
print(10 * "3") 
print("10" + 20) 
print(int("10") + 20)

1020
30
101010
3333333333


TypeError: can only concatenate str (not "int") to str

Strings are added together
integers are added together
string is multiplied with int
string cannot be added with int

Q15. Predict the output. Then explain Python's short-circuit evaluation in one line. 
print(0 or 5)                expected output is 5
print(5 or 0)                                   5
print(None or "hello")                          "hello"
print(0 and 5)                                  5
print(5 and 10)                                 10
print([] or "default")                          "default"
print([0] or "default")                         0

In [14]:
print(0 or 5) 
print(5 or 0) 
print(None or "hello") 
print(0 and 5) 
print(5 and 10) 
print([] or "default") 
print([0] or "default")

5
5
hello
0
10
default
[0]


or returns the first correct value, or the last when ntg is correct
and returns the first incorrect value, or the last if all are correct

SECTION C - Coding Practice

Q16. Swap two numbers WITHOUT using a third variable. Implement 3 different methods: (a) using arithmetic, (b) using XOR (`^`), (c) using tuple 
unpacking. Compare which is most Pythonic.

In [15]:
#arithmetic way
x, y = 5, 7
x = x + y
y = x - y
x = x - y
print("Arithmetic:", x, y)
#XOR way
x, y = 5, 7
x = x ^ y
y = x ^ y
x = x ^ y
print("XOR:", x, y)         
#Tuple way 
x, y = 5, 7
x, y = y, x
print("Tuple way swapping:", x, y) 

Arithmetic: 7 5
XOR: 7 5
Tuple way swapping: 7 5


Tuple way is the most pythonic way compared to other methods

17. Swiggy Order Calculator. Take item price and quantity as input. Compute total = price × 
quantity. Add 18% GST. Add ₹40 delivery charge if total (before delivery) is below ₹500, else delivery 
is FREE. Print all components separately and final amount in this format: 
Subtotal:    
 ₹450.00 
GST (18%):   
 ₹81.00 
Delivery:    
 ₹40.00 ------------------------ 
Total:       
 ₹571.00 

In [16]:
price = float(input("Enter item price: "))
quantity = int(input("Enter quantity: "))
subtotal = price*quantity
gst = subtotal*0.18
if subtotal < 500:
    delivery = 40.0
else:
    delivery = 0.0
total = subtotal + gst + delivery
print(f"Subtotal:    ₹{subtotal: .2f}")
print(f"GST (18%):   ₹{gst: .2f}")
print(f"Delivery:    ₹{delivery: .2f}")
print("----------------------------------")
print(f"Total:       ₹{total: .2f}")

Enter item price:  24
Enter quantity:  34


Subtotal:    ₹ 816.00
GST (18%):   ₹ 146.88
Delivery:    ₹ 0.00
----------------------------------
Total:       ₹ 962.88


18. Temperature converter. Ask user for a value and unit (C or F). Convert and print result rounded 
to 2 decimal places. Handle invalid unit input gracefully (print an error message, do NOT crash).

In [19]:
value = float(input("Enter temp value: "))
unit = input("Enter unit (C/F): ").strip().upper()
if unit == "C":
    res = (value*9/5)+32
    print(f"{res:.2f}°F")
elif unit == "F":
    res = (value-32)*5/9
    print(f"{res:.2f}°C")
else:
    print("Error: Invalid unit. Please enter 'C' or 'F'.")

Enter temp value:  23
Enter unit (C/F):  C


73.40°F


Q19. Take a 4-digit number as input. Print the sum of its digits – WITHOUT converting it to a string. 
(Use only integer arithmetic: //, %.)

In [20]:
num = int(input("Enter a 4-digit number: "))
d1 = (num//1000)
d2 = (num//100) %10  
d3 = (num//10) %10    
d4 = (num%10)           
dsum = d1+d2+d3+d4
print("Sum of digits:", dsum)

Enter a 4-digit number:  1202


Sum of digits: 5


Q20. Smart input parser. Take a single input from the user. Detect what type it is – try int first, then 
float, else treat as string. Print the value AND its detected type. Example: input "42" → int 42, input 
"3.14" → float 3.14, input "hello" → str hello.

In [21]:
a = input("Enter something: ")
try:
    value = int(a)
    print("Detected type: int,", "Value:", value)
except ValueError:
    try:
        value = float(a)
        print("Detected type: float,", "Value:", value)
    except ValueError:
        print("Detected type: str,", "Value:", a)

Enter something:  hello


Detected type: str, Value: hello


C2 – Conditionals & Logic (Q21-Q25) 

Q21. Indian Income Tax Calculator (New Regime, FY 2024–25). Take annual income as input. 
Compute tax using these slabs: 
Up to ₹3,00,000    :  Nil 
₹3,00,001 – ₹7,00,000   :   5% 
₹7,00,001 – ₹10,00,000  :  10% 
₹10,00,001 – ₹12,00,000 :  15% 
₹12,00,001 – ₹15,00,000 :  20% 
Above ₹15,00,000   :  30% 
Tax must be computed slab-wise, NOT flat. EAxample: income ₹8,00,000 → 0 on first 3L + 5% on next 4L + 10% on 
last 1L = ₹20,000 + ₹10,000 = ₹30,000. Print breakdown clearly. 

In [2]:
income = float(input("Enter your annual income (₹): "))
tax = 0
if income > 300000:
    taxable = min(income, 700000)-300000
    tax = tax + taxable*0.05
if income > 700000:
    taxable = min(income, 1000000)-700000
    tax = tax + taxable*0.10

if income > 1000000:
    taxable = min(income, 1200000)-1000000
    tax = tax + taxable*0.15

if income > 1200000:
    taxable = min(income, 1500000)-1200000
    tax = tax + taxable*0.20

if income > 1500000:
    taxable = income-1500000
    tax = tax + taxable*0.30

print(f"Total Breakdown-Tax is: ₹{tax:.2f}")

Enter your annual income (₹):  23343434


Total Breakdown-Tax is: ₹6693030.20


Q22. Validate Indian PAN card format WITHOUT using regex. Format: AAAAA9999A, first 5 are 
uppercase letters, next 4 are digits, last 1 is an uppercase letter. Total length = 10. Take input and 
print "Valid PAN" or "Invalid PAN — <reason>" where reason explains exactly what's wrong.

In [3]:
pan = input("Enter PAN number: ").strip()
if len(pan)!=10:
    print("Invalid PAN, Length must be 10")
elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN, First 5 characters must be uppercase")
elif not pan[5:9].isdigit():
    print("Invalid PAN, Characters 6 to 9 must be digits")
elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN, Last character must be an uppercase")
else:
    print("Valid PAN")

Enter PAN number:  DNDKK3737D


Valid PAN


Q23. Bengaluru BESCOM Electricity Bill (LT-2 Residential). Take units consumed as input. Charges: 
0 – 50 units : ₹4.10 per unit 
51 – 100 units : ₹5.55 per unit 
101 – 200 units : ₹7.10 per unit 
Above 200 units : ₹8.15 per unit 
Add fixed charge: ₹110. Add 6% government tax on (energy charges + fixed charge). Print itemized bill.

In [4]:
units = int(input("Enter units consumed: "))
charge = 0
if units <= 50:
    charge = units*4.10
elif units <= 100:
    charge = (50*4.10)+(units-50)*5.55
elif units <= 200:
    charge = (50*4.10)+(50*5.55)+(units-100)*7.10
else:
    charge = (50*4.10)+(50*5.55)+(100*7.10)+(units-200)*8.15
fixed = 110
tax = 0.06*(charge+fixed)
total = charge + fixed + tax
print(f"Energy Charges: ₹{charge:.2f}")
print(f"Fixed Charge:   ₹{fixed:.2f}")
print(f"Govt Tax:  ₹{tax:.2f}")
print(f"Total Bill:     ₹{total:.2f}")

Enter units consumed:  344


Energy Charges: ₹2366.10
Fixed Charge:   ₹110.00
Govt Tax:  ₹148.57
Total Bill:     ₹2624.67


Q24. Cricket Strike Rate Classifier. Take runs scored and balls faced. Compute strike rate = 
(runs/balls) × 100. Classify: 
SR > 150 →  Explosive (T20 finisher) 
100 < SR ≤ 150 →  Aggressive (Top order T20) 
75 ≤ SR ≤ 100  →  Steady (ODI anchor) 
SR < 75 →  Defensive (Test match) 
Edge case: handle balls = 0 (do not crash, print message instead). 

In [5]:
runs = int(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))
if balls == 0:
    print("Error, Balls faced cannot be zero")
else:
    sr = (runs/balls)*100
    print(f"Strike Rate: {sr:.2f}")
    if sr>150:
        print("Explosive")
    elif sr>100:
        print("Aggressive")
    elif sr>=75:
        print("Steady")
    else:
        print("Defensive")

Enter runs scored:  343
Enter balls faced:  333


Strike Rate: 103.00
Aggressive


Q25. BMI Calculator (Indian standards). Take weight (kg) and height (cm). Compute BMI = weight / 
(height_in_meters)². Classify using Indian (not WHO) BMI categories: 
BMI < 18.5   →  Underweight 
18.5 – 22.9   →  Normal (Indian range — narrower than WHO) 
23.0 – 24.9   →  Overweight 
25.0 – 29.9   →  Obese Class I 
BMI ≥ 30    →  Obese Class II

In [6]:
weight = float(input("Enter weight (kg): "))
heightcm = float(input("Enter height (cm): "))
heightm = heightcm / 100   # convert cm to meters
bmi = weight / (heightm ** 2)
print(f"BMI: {bmi:.2f}")
if bmi < 18.5:
    print("Underweight")
elif bmi <= 22.9:
    print("Normal")
elif bmi <= 24.9:
    print("Overweight")
elif bmi <= 29.9:
    print("Obese Class I")
else:
    print("Obese Class II")

Enter weight (kg):  33
Enter height (cm):  66


BMI: 75.76
Obese Class II


C3 – Nested Loop Patterns (Q26-Q30) 
Take N (size) as input where applicable. Use only `print()`, `for` / `while`, and `range()`. No string multiplication 
shortcuts where the pattern can be drawn with loops. 
Q26. Print this pattern for N = 5: 
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5

In [7]:
n=int(input("Enter value of n: "))
for i in range(1, n+1):        
    for j in range(1, i+1):  
        print(j, end=" ")
    print()  

Enter value of n:  5


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


Q27. Print this number diamond for N = 5 (the digits go up to N in the middle row): 
    1 
   1 2 1 
  1 2 3 2 1 
 1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
 1 2 3 4 3 2 1 
  1 2 3 2 1 
   1 2 1 
    1 

In [10]:
n = int(input("Enter n: "))
for i in range(1, n+1):
    print(" " * (n-i), end="")     
    for j in range(1, i+1):         
        print(j, end=" ")
    for j in range(i-1, 0, -1):    
        print(j, end=" ")
    print()

for i in range(n-1, 0, -1):
    print(" " * (n-i), end="")      
    for j in range(1, i+1):         
        print(j, end=" ")
    for j in range(i-1, 0, -1):      
        print(j, end=" ")
    print()

Enter n:  5


    1 
   1 2 1 
  1 2 3 2 1 
 1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
 1 2 3 4 3 2 1 
  1 2 3 2 1 
   1 2 1 
    1 


Q28. Print a hollow square of size N (only the border is *, inside is blank). For N = 5: 
* * * * * 
*       * 
*       * 
*       * 
* * * * *

In [12]:
n=int(input("Enter n: "))
for i in range(n):
    for j in range(n):
        if i == 0 or i == n-1 or j == 0 or j == n-1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

Enter n:  5


* * * * * 
*       * 
*       * 
*       * 
* * * * * 


Q29. Print the first 5 rows of Pascal's Triangle: 
        1 
       1 1 
      1 2 1 
     1 3 3 1 
    1 4 6 4 1 
You may use any approach (formula-based or direct calculation), but no math.comb() or any imported function.

In [13]:
rows = 5
for i in range(rows):
    print(" "*(rows - i), end="")
    val = 1
    for j in range(i+1):
        print(val, end=" ")
        val = val*(i - j) // (j + 1)
    print()

     1 
    1 1 
   1 2 1 
  1 3 3 1 
 1 4 6 4 1 


Q30. Print this character pattern for N = 5 – letters go up to the N-th alphabet: 
A 
A B 
A B C 
A B C D 
A B C D E

In [18]:
n=int(input("Enter n: "))
for i in range(1, n+1):
    for j in range(i):
        print(chr(ord('A')+j), end=" ")
    print()

Enter n:  5


A 
A B 
A B C 
A B C D 
A B C D E 


C4 – Loop Logic (Q31-Q36) 
Q31. Find all Armstrong numbers between 1 and 9999. (An n-digit number is Armstrong if the sum of 
its digits each raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.) Print them 
in a clean comma-separated list with a count at the end.

In [20]:
armstrong = []
for num in range(1, 10000):
    digits = str(num)
    n = len(digits)
    total = 0
    for d in digits:
        total=total+ int(d) ** n
    if total == num:
        armstrong.append(num)
print("Armstrong Numbers (1–9999):")
print(", ".join(str(x) for x in armstrong))
print("Count =", len(armstrong))

Armstrong Numbers (1–9999):
1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474
Count = 16


Q32. Take N as input. Print the first N terms of the Fibonacci series. Also compute and print the SUM 
of those N terms. Do NOT use recursion. Edge case: N = 0 should print nothing, sum = 0. N = 1 should 
print just 0. 

In [22]:
n=int(input("Enter n: "))
a, b = 0, 1
sum_fib = 0
for i in range(n):
    print(a, end=" ")
    sum_fib = sum_fib+a
    a, b = b, a + b
print("Sum =", sum_fib)

Enter n:  5


0 1 1 2 3 Sum = 7


Q33. Prime check, optimized. Take a number N. Check if it is prime by iterating only up to √N. Then, 
print the SUM of all primes between 2 and N (inclusive). Do not use any library. 

In [25]:
n= int(input("Enter value: "))
def is_prime(num):
    if num<2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True
print("Prime" if is_prime(n) else "Not Prime")
prime_sum = 0
for k in range(2, n+1):
    if is_prime(k):
        prime_sum = prime_sum + k
print("Sum =", prime_sum)

Enter value:  5


Prime
Sum = 10


Q34. Take a number as input. Reverse it WITHOUT converting to string. Then check if the original and 
reversed are equal (palindrome). Handle negative numbers, they should be considered NOT 
palindrome (because of the minus sign). Examples: 121 → palindrome, 123 → not palindrome, -121 
→ not palindrome. 

In [26]:
n = int(input("Enter number: "))
if n < 0:
    print("Not Palindrome")  
else:
    original = n
    rev = 0
    while n > 0:
        digit = n % 10
        rev = rev * 10 + digit
        n //= 10
    print("Palindrome" if rev == original else "Not Palindrome")

Enter number:  5


Palindrome


Q35. Take two positive integers. Compute their HCF (Highest Common Factor) using Euclidean 
algorithm with a `while` loop. Then compute LCM using the relation: HCF × LCM = a × b. Do not use 
math.gcd. 

In [27]:
a = int(input("Enter 1st num: "))
b = int(input("Enter 2nd num: "))
x, y = a, b
while y != 0:
    x, y = y, x % y
hcf = x
lcm = (a * b)//hcf
print("HCF =", hcf)
print("LCM =", lcm)

Enter 1st num:  45
Enter 2nd num:  45


HCF = 45
LCM = 45


Q36. String scanner, single pass. Take a sentence (e.g., a Swiggy review like "Order came on time, 
food was hot, packaging 10/10!"). In ONE pass through the string, count: total characters, total 
words, vowels (a, e, i, o, u - case-insensitive), consonants, digits, spaces, and special characters. Print 
all counts. 

In [28]:
text = input("Enter a sentence: ")
chars=words=vowels=consonants=digits=spaces=specials=0
in_word = False
for ch in text:
    chars=chars+1
    if ch.isalpha():
        if ch.lower() in "aeiou":
            vowels=vowels+1
        else:
            consonants= consonants+1
        if not in_word:
            words=words+1
            in_word = True
    else:
        in_word = False
        if ch.isdigit():
            digits= digits+ 1
        elif ch == " ":
            spaces=spaces+ 1
        else:
            specials=specials+ 1
print("Characters:", chars)
print("Words:", words)
print("Vowels:", vowels)
print("Consonants:", consonants)
print("Digits:", digits)
print("Spaces:", spaces)
print("Specials:", specials)

Enter a sentence:  fkdjj jdvjd djvijvi


Characters: 19
Words: 3
Vowels: 2
Consonants: 15
Digits: 0
Spaces: 2
Specials: 0


Q37. Take 10 student marks (out of 100) as input, space-separated on one line, parse with split() and 
map(). Without using sort() or sorted(), find: (a) maximum, (b) minimum, (c) average, (d) count of 
students above average, (e) the SECOND highest mark.

In [29]:
marks = list(map(int, input("Enter 10 marks: ").split()))
maxi = marks[0]
mini = marks[0]
for m in marks:
    if m > maxi:
        maxi = m
    if m < mini:
        mini = m
total = 0
for m in marks:
    total = total+ m
average = total / len(marks)

count_above = 0
for m in marks:
    if m > average:
        count_above=count_above+ 1
        
highest = second = -1
for m in marks:
    if m > highest:
        second = highest
        highest = m
    elif m > second and m != highest:
        second = m

print("Maximum:", maxi)
print("Minimum:", mini)
print("Average:", average)
print("Count above average:", count_above)
print("Second highest:", second)

Enter 10 marks:  34 42 43 34 87 67 88 86 57 55


Maximum: 88
Minimum: 34
Average: 59.3
Count above average: 4
Second highest: 87


Q38. Word Frequency Analyzer for Swiggy reviews. Take a review sentence. Find the frequency of 
each word (case-insensitive, "Food" and "food" should be counted together). Print words sorted by 
frequency in descending order. Also print the MOST frequent word and its count. Use a dict. 

In [ ]:
review = input("Enter review: ").lower().split()
freq = {}
for w in review:
    if w in freq:
        freq[w] =freq[w]+ 1
    else:
        freq[w] = 1
items = sorted(freq.items(), key=lambda x: x[1], reverse=True)
for word, count in items:
    print(word, ":", count)
print("Most frequent word =", items[0][0], "Count =", items[0][1])

Q39. Indian States CRUD. Pre-populate a dict with 5 Indian states and their capitals (e.g., Karnataka 
→ Bengaluru, Maharashtra → Mumbai). Then build a menu-driven program: 
1. Add a new state-capital pair 
2. Update an existing capital 
3. Delete a state 
4. Search a state (return capital, or 'Not found') 
5. Display all states sorted alphabetically 
6. Exit 

In [1]:
states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Tamil Nadu": "Chennai",
    "Kerala": "Thiruvananthapuram",
    "Delhi": "New Delhi"
}
while True:
    print("1. Add new state : capital")
    print("2. Update capital")
    print("3. Delete state")
    print("4. Search state")
    print("5. Display all states")
    print("6. Exit")

    choice = int(input("Enter choice: "))

    if choice == 1:
        state = input("Enter state: ")
        capital = input("Enter capital: ")
        states[state] = capital
        print("Added successfully")

    elif choice == 2:
        state = input("Enter state to update: ")
        if state in states:
            capital = input("Enter new capital: ")
            states[state] = capital
            print("Updated successfully")
        else:
            print("State not found.")

    elif choice == 3:
        state = input("Enter state to delete: ")
        if state in states:
            del states[state]
            print("Deleted successfully!")
        else:
            print("State not found.")

    elif choice == 4:
        state = input("Enter state to search: ")
        if state in states:
            print("Capital =", states[state])
        else:
            print("Not found.")

    elif choice == 5:
        print("\nStates and Capitals:")
        for s in sorted(states.keys()):
            print(s, ":", states[s])

    elif choice == 6:
        print("Exited")
        break

    else:
        print("Invalid choice")


1. Add new state : capital
2. Update capital
3. Delete state
4. Search state
5. Display all states
6. Exit


Enter choice:  1
Enter state:  Karnataka
Enter capital:  Bengaluru


Added successfully
1. Add new state : capital
2. Update capital
3. Delete state
4. Search state
5. Display all states
6. Exit


Enter choice:  5



States and Capitals:
Delhi : New Delhi
Karnataka : Bengaluru
Kerala : Thiruvananthapuram
Maharashtra : Mumbai
Tamil Nadu : Chennai
1. Add new state : capital
2. Update capital
3. Delete state
4. Search state
5. Display all states
6. Exit


Enter choice:  6


Exited


Q40. Set Operations. Students in Section A know languages = {Python, Java, C++, SQL}. Students in 
Section B know = {Java, JavaScript, Python, Go, SQL}. Using ONLY set operations, find: 
(a) Languages known by BOTH sections 
(b) Languages known ONLY by Section A 
(c) Languages known ONLY by Section B 
(d) Total unique languages across both sections 
(e) Languages exclusive to one section but not both (symmetric difference)

In [2]:
A = {"Python", "Java", "C++", "SQL"}
B = {"Java", "JavaScript", "Python", "Go", "SQL"}
print("Both:", A&B)
print("Only A:", A-B)
print("Only B:", B-A)
print("Total unique:", A|B)
print("Exclusive:", A^B)

Both: {'Python', 'Java', 'SQL'}
Only A: {'C++'}
Only B: {'JavaScript', 'Go'}
Total unique: {'JavaScript', 'Python', 'C++', 'SQL', 'Go', 'Java'}
Exclusive: {'JavaScript', 'Go', 'C++'}


Q41. TCS stock prices for a week stored as a tuple: `prices = (3845, 3902, 3878, 3955, 4012, 3998, 
4055)` (Mon to Sun in ₹). Find: (a) maximum price and which day, (b) minimum price and which day, 
(c) average, (d) biggest single-day gain (and between which days), (e) total volatility = sum of 
absolute day-to-day price changes. 

In [3]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon","Tue","Wed","Thu","Fri","Sat","Sun")
max_price = max(prices)
max_day = days[prices.index(max_price)]
min_price = min(prices)
min_day = days[prices.index(min_price)]
avg = sum(prices) / len(prices)
big_gain = 0
gain_days=("","")
for i in range(1,len(prices)):
    gain=prices[i]-prices[i-1]
    if gain>big_gain:
        big_gain = gain
        gain_days = (days[i-1], days[i])
volatility = sum(abs(prices[i]-prices[i-1]) for i in range(1,len(prices)))
print("Max:", max_price, "on", max_day)
print("Min:", min_price, "on", min_day)
print("Average:", avg)
print("Biggest gain:", big_gain, "from", gain_days[0], "to", gain_days[1])
print("Volatility:", volatility)

Max: 4055 on Sun
Min: 3845 on Mon
Average: 3949.285714285714
Biggest gain: 77 from Wed to Thu
Volatility: 286


Q42. Given a list of 20 integers (you generate or hardcode them, some duplicates), produce: (a) the 
set of unique numbers, (b) the list of numbers appearing more than once, (c) the list of numbers 
appearing EXACTLY once. Do this WITHOUT importing Counter or any other library. 

In [4]:
nums = [5, 12, 7, 5, 9, 12, 18, 7, 21, 30,
        9, 40, 18, 25, 30, 50, 60, 25, 70, 80]
unique = set(nums)
duplicates = []
for n in unique:
    if nums.count(n) > 1:
         duplicates.append(n)
singles = []
for n in unique:
    if nums.count(n) == 1:
        singles.append(n)

print("Unique numbers:", unique)
print("Duplicates:", duplicates)
print("Singles:", singles)

Unique numbers: {5, 70, 7, 40, 9, 12, 80, 18, 50, 21, 25, 60, 30}
Duplicates: [5, 7, 9, 12, 18, 25, 30]
Singles: [70, 40, 80, 50, 21, 60]


C6 – Strings (Q43-Q45) 
Q43. Smart Palindrome Checker. Take a sentence as input. Check if it is a palindrome IGNORING: 
case, spaces, and all special characters (punctuation). Examples that should return TRUE: "A man, a 
plan, a canal: Panama", "Race car", "No 'x' in Nixon". Hint: build a cleaned version of the string first.

In [6]:
sentence = input("Enter a sentence: ")
cleaned = ""
for ch in sentence:
    if ch.isalnum():   
        cleaned=cleaned+ch.lower()
if cleaned == cleaned[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter a sentence:  Hisih


Palindrome


Q44. Manual Title Case. Take a sentence (e.g., "hello world from bengaluru"). Capitalize the first 
letter of EACH word, but do NOT use .title() or .capitalize(). Use only .upper() / .lower() and string 
indexing. Output: "Hello World From Bengaluru".

In [7]:
sentence = input("Enter a sentence: ").split()
result = []
for word in sentence:
    new_word = word[0].upper() + word[1:].lower()
    result.append(new_word)
print(" ".join(result))

Enter a sentence:  wieii


Wieii


Q45. Caesar Cipher Encryptor. Take a message and a shift value N as input. Encrypt by shifting each 
letter forward by N positions in the alphabet (wrapping around, Z + 1 = A). Preserve case. Keep digits, 
spaces, and special characters UNCHANGED. Example: "Hello, India!" with shift 3 → "Khoor, Lqgld!" 

In [9]:
message = input("Enter message: ")
shift = int(input("Enter shift value: "))
encrypted = ""
for ch in message:
    if 'A' <= ch <= 'Z':   
        encrypted = encrypted+chr((ord(ch)-ord('A')+shift)%26+ord('A'))
    elif 'a' <= ch <= 'z':
        encrypted= encrypted+ chr((ord(ch)-ord('a')+shift)%26+ord('a'))
    else:
        encrypted += ch
print("Encrypted message:", encrypted)

Enter message:  duddhedh
Enter shift value:  4


Encrypted message: hyhhlihl


C7 – Functions (Q46-Q47) 
Q46. Write a function `calculate_gst(amount, gst_rate=18, gst_inclusive=False)`: - If gst_inclusive=False: amount is base, add GST on top -
If gst_inclusive=True: amount already includes GST, extract it - Return a tuple: (base_amount, gst_amount, total_amount) - All values rounded
to 2 decimals 
Test cases: 
calculate_gst(1000) → (1000.00, 180.00, 1180.00) 
calculate_gst(1180, gst_inclusive=True) → (1000.00, 180.00, 1180.00) 
calculate_gst(500, gst_rate=5)   → (500.00, 25.00, 525.00)

In [10]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):
    if not gst_inclusive:
        base = amount
        gst = round(base*gst_rate/100, 2)
        total = round(base+gst, 2)
    else:
        total = amount
        base = round(total/(1+gst_rate/100), 2)
        gst = round(total-base, 2)
    return (round(base, 2), round(gst, 2), round(total, 2))

print(calculate_gst(1000))                    
print(calculate_gst(1180, gst_inclusive=True)) 
print(calculate_gst(500, gst_rate=5))        

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


Q47. Write a RECURSIVE function `power(base, exp)` that computes base raised to exp, WITHOUT 
using the `**` operator and WITHOUT using `pow()`. Handle exp = 0 (return 1) and negative exp 
(return 1/power(base, -exp)). Test with: power(2, 10), power(5, 0), power(3, -2).

In [11]:
def power(base, exp):
    if exp==0:
        return 1
    elif exp<0:
        return 1/power(base, -exp)
    else:
        return base*power(base, exp - 1)
print(power(2, 10))   
print(power(5, 0))  
print(power(3, -2)) 

1024
1
0.1111111111111111


C8 – NumPy Foundations (Q48-Q50) 
Q48. Identity Matrix Manipulations. Using NumPy: (a) create a 5×5 identity matrix using np.eye(), (b) 
multiply every element by 10, (c) transpose it (yes, it looks the same, explain in a comment WHY 
transpose of an identity is itself), (d) compute the sum of diagonal elements, (e) compute the sum of 
all elements. Print each step. 

In [16]:
import numpy as np
Identity1 = np.eye(5)
print("Identity:\n", Identity1)
Identity2 = Identity1 * 10
print("\nMultiplied by 10:\n", Identity2)
Identity3 = Identity2.T
print("\nTranspose:\n", Identity3)
print("\nDiagonal sum:", np.trace(Identity2))
print("Total sum:", np.sum(Identity2))

Identity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Multiplied by 10:
 [[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose:
 [[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Diagonal sum: 50.0
Total sum: 50.0


Q49. Zomato Weekly Sales Analytics. Create a NumPy array of 7-day Zomato Bengaluru sales (in ₹): 
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400]) 
Mon    
Tue    
Wed    
Thu    
Fri    
Without using loops, compute and print: 
Sat    
Sun 
(a) Total weekly sales 
(b) Daily average 
(c) The day (Mon/Tue/...) with maximum sales 
(d) Number of days with sales above the weekly average 
(e) Percentage growth from Monday to Sunday 
(f) An array of day-on-day % changes (length 6) 

In [17]:
import numpy as np
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
print("Total sales:", sales.sum())
avg = sales.mean()
print("Daily average:", avg)
max_day = days[sales.argmax()]
print("Max sales day:", max_day,"=", sales.max())
print("Days above average:", (sales>avg).sum())
growth = ((sales[-1] - sales[0]) / sales[0])*100
print("Growth Mon→Sun (%):", round(growth,2))
pct_changes = ((sales[1:] - sales[:-1])/sales[:-1])*100
print("Day-on-day % changes:", pct_changes)

Total sales: 150200
Daily average: 21457.14285714286
Max sales day: Sat = 35200
Days above average: 3
Growth Mon→Sun (%): 136.67
Day-on-day % changes: [ 54.16666667 -23.24324324  55.63380282 -10.40723982  77.77777778
 -19.31818182]


Q50. The Border Pattern Challenge – NO explicit loops. Create a 5×5 NumPy array where the BORDER 
is 1 and the INTERIOR is 0. Output should look like: 
[[1 1 1 1 1] 
[1 0 0 0 1] 
[1 0 0 0 1] 
[1 0 0 0 1] 
[1 1 1 1 1]] 
Constraint: You may use np.ones(), np.zeros(), and slicing, but NO `for`, NO `while`, NO list comprehension. Only 
NumPy operations. 

In [15]:
import numpy as np
arr = np.zeros((5,5), dtype=int)
arr[0] = 1       
arr[-1] = 1     
arr[:,0] = 1     
arr[:,-1] = 1    
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


If you genuinely solved all 50 questions, you are interview-ready for Week 1 topics. Now flip the table: pick any 5 
questions and EXPLAIN your solution out loud, as if to a panel. That's where most candidates fail, they can code, 
but they cannot articulate.

Q41 – Stock Prices Analysis
I stored prices in a tuple and mapped them to weekdays.
Used max() and min() to find highest and lowest prices, then .index() to get the day.
Average was sum(prices)/len(prices).
Biggest gain was checked by differences between consecutive days.

Q43 – Smart Palindrome Checker
Took input string, cleaned it by keeping only alphanumeric characters using .isalnum() and converted to lowercase.
Compared cleaned string with its reverse [::-1].
If equal then it is palindrome, else it is not.

Split sentence into words with .split().
For each word, I made first letter uppercase with word[0].upper() and rest lowercase with word[1:].lower().
Joined back with " ".join(result).

Q47 – Recursive Power Function
Defined power(base, exp).
Base case: if exp=0 then it should return 1.
If exp<0 then return 1/power(base,-exp).
Else then it should return base * power(base, exp-1)